### ISSUE TITLE
Constructors with given precision

### ISSUE THREAD

**Issue by dpsanders** [JuliaArbTypes/ArbFloats.jl#12]
Would be useful to have
```
julia> ArbFloat("1.3", 100)
```
to make an `ArbFloat` with given precision.

cf. https://github.com/JuliaLang/julia/pull/17217 for BigFloats.

**Comment by JeffreySarnoff** [comment]
Your notes were helpful, got to most and still looking at rounding (it is
not simple because it is not well defined given there is a radius which
absorbs any lsb rounding  -- but it is expected, so I am going to round the
midpoint and restore the radius ). And round(x,y)

pick one

(a)
ArbFloat{200}(12)  # use the specified precision, at run time
ArbFloat(200,"12") # use the specified precision, at run time

(b)
ArbFloat{200}(12)  # use the specified precision, at run time
ArbFloat("12",200) # use the specified precision, at run time


Also take a look at ArbDecimals, I am getting ready to register that for
v0.6.  While it is less broad than ArbFloat -- what it does is good and
coded with some lessons learned.

On Tue, Jan 24, 2017 at 10:35 AM, David P. Sanders <notifications@github.com

**Comment by JeffreySarnoff** [comment]
ArbFloat("12", 256)
typeof(ArbFloat(12, 128)) == ArbFloat{128}
